Blog/Models/Membership.cs
namespace Blog.Models
{
    public class Membership
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Link { get; set; }
        public bool IsEnabled { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}

Blog/Controllers/MembershipController.cs
using Blog.Interfaces;
using Blog.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Controllers
{
    [Authorize(Roles = "Admin")]
    public class MembershipController : Controller
    {
        private readonly IMembership _membership;


        public MembershipController(IMembership membership)
        {
            _membership = membership;
        }


        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var allMemberships = await _membership.GetAllMembershipsAsync();
            return View(allMemberships);
        }

        [HttpGet]
        public async Task<IActionResult> Generate([FromServices] IHttpContextAccessor httpContextAccessor)
        {
            string code = Guid.NewGuid().ToString();
            string link = HttpContext.Request.Scheme + "://" + httpContextAccessor.HttpContext.Request.Host.Value + "/register?code=" + code;

            var membership = new Membership
            {
                CreatedDate = DateTime.Now,
                IsEnabled = true,
                Code = code,
                Link = link
            };
            await _membership.AddMembershipAsync(membership);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Delete(int membershipId)
        {
            var currentMembership = await _membership.GetMembershipAsync(membershipId);
            if (currentMembership != null)
            {
                await _membership.DeleteMembershipAsync(currentMembership);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Blog/Views/Membership/Index.cshtml
@model IEnumerable<Membership>
@{
    ViewBag.Title = "Генерация приглашений";
}
<div class="container px-4 py-5" id="hanging-icons">
    <h2 class="pb-2 border-bottom">Генерация приглашений</h2>
    <a asp-controller="Home" asp-action="Index">Главная</a> / <a asp-controller="Users" asp-action="Index">Все пользователи</a>
    <div class="row g-4 py-5 row-cols-1">
        <div>
            <a asp-controller="Membership" asp-action="Generate" class="btn btn-primary">Сгенерировать новое приглашение</a>
        </div>
        <div class="p-5 mb-4 bg-light rounded-3 ovx">
            <table class="table table-hover">
                <tr><th>Ссылка</th><th>Дата генерации</th><th>Статус</th><th></th></tr>
                @foreach (var membership in Model)
                {
                    <tr>
                        <td>@membership.Link</td>
                        <td>@membership.CreatedDate</td>
                        @if (@membership.IsEnabled)
                        {
                            <td class="text-success">Активное</td>
                        }
                        else
                        {
                            <td class="text-danger">Не активное</td>
                        }
                        <td>
                            <form asp-controller="Membership" asp-action="Delete" asp-route-membershipId="@membership.Id" method="post">
                                @Html.AntiForgeryToken()
                                <button type="submit" class="btn btn-sm btn-danger">Удалить</button>
                            </form>
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>